apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: dineswift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: dineswift/restaurant-service:latest
        ports:
        - containerPort: 5002
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: dineswift-secrets
              key: MONGO_URI
        - name: PORT
          value: "5002"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: dineswift
spec:
  selector:
    app: restaurant-service
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP