apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: dineswift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: dineswift/user-service:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: dineswift-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: dineswift-secrets
              key: JWT_SECRET
        - name: PORT
          value: "5001"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: dineswift
spec:
  selector:
    app: user-service
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP