apiVersion: v1
kind: Secret
metadata:
  name: dineswift-secrets
  namespace: dineswift
type: Opaque
data:
  MONGO_URI: mongodb+srv://nithika151:1234@dineswift.zjw7y.mongodb.net/?retryWrites=true&w=majority&appName=DineSwift
  JWT_SECRET: jwttokenkey
  STRIPE_SECRET_KEY: <base64-encoded-stripe-key>